runtime: ruby32
env: standard

instance_class: F1

beta_settings:
  cloud_sql_instances: news-aggregator-447817:us-central:desafio-impulso-db

entrypoint: bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0

automatic_scaling:
  min_instances: 0
  max_instances: 2