version: "3.9"

services:

  postgres:
    container_name: desafio_impulso-db
    image: postgres:14.2
    environment:
      POSTGRES_USER: desafio_impulso
      POSTGRES_PASSWORD: desafio_impulso
    ports:
      - '5442:5432'
    volumes:
      - desafio_impulso-postgres:/var/lib/postgresql/data

  redis:
    container_name: desafio_impulso-redis
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - desafio_impulso-redis:/var/lib/redis/data
    command: 'redis-server'

  desafio_impulso:
    container_name: desafio_impulso-app
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid || true && bin/rails s -p 3333 -b '0.0.0.0'"
    volumes:
      - .:/desafio_impulso
    links:
      - postgres
      - redis
    ports:
      - '3333:3333'
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  desafio_impulso-postgres:
  desafio_impulso-redis:
