default: &default
  adapter: postgresql
  encoding: unicode
  pool: 55

development:
  <<: *default
  url: <%= ENV['DATABASE_URL']&.gsub('?', '_development?') || 'postgresql://localhost:5432/desafio_impulso_development' %>

test:
  <<: *default
  url: <%= ENV['DATABASE_URL']&.gsub('?', '_test?') || 'postgresql://localhost:5432/desafio_impulso_test' %>

staging:
  <<: *default
  url: <%= ENV['DATABASE_URL']&.gsub('?', '_staging?') %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
