name: "RSpec Tests and Simplecov coverage"
on:
  pull_request:
    branches: [ "main" ]

env:
  RAILS_ENV: test
  DATABASE_URL: "postgres://rails:password@localhost:5432/desafio_impulso_test"
  REDIS_URL: "redis://localhost:6379/0"
  ELASTICSEARCH_URL: "http://localhost:9200"

jobs:
  rspec:
    permissions: write-all
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: desafio_impulso_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
      redis:
        image: redis:alpine3.16
        ports: ["6379:6379"]
        options: --entrypoint redis-server
      elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
        ports: ["9200:9200", "9300:9300"]
        env:
          discovery.type: single-node
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Set up database schema
        run: |
          bin/rails db:drop
          bin/rails db:create
          bin/rails db:migrate

      - name: Run Assets Precompile
        run: |
          bin/rails assets:precompile

      - name: Run RSpec tests
        run: bundle exec rspec

      - uses: joshmfrankel/simplecov-check-action@main
        with:
          minimum_suite_coverage: 85
          minimum_file_coverage: 70
          github_token: ${{ secrets.GITHUB_TOKEN }}
